[theme]
primaryColor = "#CC231E"
backgroundColor = "#0F8A5F"
secondaryBackgroundColor = "#34A65F"
textColor = "#FFFFFF"
font = "sans serif"

[server]
runOnSave = true
fileWatcherType = "poll"

[browser]
gatherUsageStats=false